# Generated by Django 5.1.1 on 2024-09-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='sender',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='receiver',
            new_name='to_user',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
